# imports

import os

import httpx
import requests
from dotenv import load_dotenv
from openai import OpenAI, APIStatusError, APIConnectionError
from IPython.display import Markdown, display
from openai import OpenAI
import gradio as gr

#load env
load_dotenv(override=True)
#keys
openai_api_key = os.getenv('OPENAI_API_KEY')
anthropic_api_key = os.getenv('ANTHROPIC_API_KEY')
google_api_key = os.getenv('GEMINI_API_KEY')
deepseek_api_key = os.getenv('DEEPSEEK_API_KEY')
groq_api_key = os.getenv('GROQ_API_KEY')
grok_api_key = os.getenv('GROK_API_KEY')
openrouter_api_key = os.getenv('OPENROUTER_API_KEY')
api_key = 'ollama'


if google_api_key:
    print(f"Google API Key exists and begins {google_api_key[:2]}")
else:
    print("Google API Key not set (and this is optional)")
if api_key:
    print(f"Ollama API Key exists and begins {api_key[:5]}")
else:
    print("Ollama API Key not set")

# Connect to OpenAI client library
# A thin wrapper around calls to HTTP endpoints
#openai = OpenAI()

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai/"
OLLAMA_BASE_URL = "http://localhost:11434/v1"
ollama = OpenAI(base_url=OLLAMA_BASE_URL, api_key="ollama")
gemini = OpenAI(base_url=GEMINI_BASE_URL, api_key=google_api_key)

#prompt
system_message = "You are a helpful assistant in a clothes store. You should try to gently encourage \
the customer to try items that are on sale. Hats are 60% off, and most other items are 50% off. \
For example, if the customer says 'I'm looking to buy a hat', \
you could reply something like, 'Wonderful - we have lots of hats - including several that are part of our sales event.'\
Encourage the customer to buy hats if they are unsure what to get."

system_message += "\nIf the customer asks for shoes, you should respond that shoes are not on sale today, \
but remind the customer to look at hats!"

def chat(message, history):
    history = [{"role":h["role"], "content":h["content"]} for h in history]
    relevant_system_message = system_message
    if 'belt' in message.lower():
        relevant_system_message += " The store does not sell belts; if you are asked for belts, be sure to point out other items on sale."

    messages = [{"role": "system", "content": relevant_system_message}] + history + [{"role": "user", "content": message}]

    try:
        print("🚀 Attempting to connect to Cloud API (Gemini 3.5 Flash)...")
        # Try calling the free cloud model first
        # use below for using Gemini
        stream = gemini.chat.completions.create(model="gemini-3.5-flash", messages=messages,stream=True,
                                                  timeout=10.0  # Prevents script hanging if internet is sluggish
                                                  )
        print("✅ Success! Response generated by Gemini Cloud.")
        #display(Markdown(response.choices[0].message.content))
        result = ""
        for chunk in stream:
            result += chunk.choices[0].delta.content or ""
            yield result

    except (APIStatusError, APIConnectionError, httpx.ConnectError) as e:
        # This block catches rate limits (429), internet outages, or Google server issues
        print(f"\n⚠️ Cloud API failed or limit reached! Reason: {e}")
        print("🔄 Switching to local fallback model (Qwen 2.5 Coder)...")
        try:
            # Call your local Ollama instance running offline on your machine
            # use below for using Ollama
            stream = ollama.chat.completions.create(model="qwen2.5-coder:1.5b", messages=messages,stream=True)
            print("✅ Success! Response generated by your local machine (Ollama).")
            #display(Markdown(response.choices[0].message.content))
            result = ""
            for chunk in stream:
                result += chunk.choices[0].delta.content or ""
                yield result

        except Exception as local_err:
            print(f"❌ Both cloud and local models failed. Is Ollama running? Error: {local_err}")



    #stream = gemini.chat.completions.create(model="gemini-3.5-flash", messages=messages, stream=True)
    #stream = gemini.chat.completions.create(model="gemini-3.5-flash", messages=messages, stream=True)


view = gr.ChatInterface(fn=chat)
view.launch(inbrowser=True)